### ISSUE TITLE
Error con SECRET_KEY local

### ISSUE THREAD

**Issue by Gnoq** [bvsf/sigcaw#55]
Buenas tardes! Disculpen que moleste un feriado y plena siesta, pero me puse a tocar código. Hice un pull de upstream y origin a mi máquina, creé una rama nueva, agregé código, y al momento de tirar un makemigrations y migrate me salta éste error:

Traceback (most recent call last):
  File "./manage.py", line 16, in <module>
    execute_from_command_line(sys.argv)
  File "/home/emicugno/workspace/projects/p_sigcaw/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/emicugno/workspace/projects/p_sigcaw/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/emicugno/workspace/projects/p_sigcaw/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 195, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/home/emicugno/workspace/projects/p_sigcaw/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 39, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/home/emicugno/workspace/projects/p_sigcaw/env/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/emicugno/workspace/projects/p_sigcaw/env/lib/python3.5/site-packages/django/core/management/commands/makemigrations.py", line 8, in <module>
    from django.db.migrations.autodetector import MigrationAutodetector
  File "/home/emicugno/workspace/projects/p_sigcaw/env/lib/python3.5/site-packages/django/db/migrations/autodetector.py", line 14, in <module>
    from django.db.migrations.questioner import MigrationQuestioner
  File "/home/emicugno/workspace/projects/p_sigcaw/env/lib/python3.5/site-packages/django/db/migrations/questioner.py", line 12, in <module>
    from .loader import MigrationLoader
  File "/home/emicugno/workspace/projects/p_sigcaw/env/lib/python3.5/site-packages/django/db/migrations/loader.py", line 10, in <module>
    from django.db.migrations.recorder import MigrationRecorder
  File "/home/emicugno/workspace/projects/p_sigcaw/env/lib/python3.5/site-packages/django/db/migrations/recorder.py", line 12, in <module>
    class MigrationRecorder(object):
  File "/home/emicugno/workspace/projects/p_sigcaw/env/lib/python3.5/site-packages/django/db/migrations/recorder.py", line 26, in MigrationRecorder
    class Migration(models.Model):
  File "/home/emicugno/workspace/projects/p_sigcaw/env/lib/python3.5/site-packages/django/db/migrations/recorder.py", line 27, in Migration
    app = models.CharField(max_length=255)
  File "/home/emicugno/workspace/projects/p_sigcaw/env/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 1072, in __init__
    super(CharField, self).__init__(*args, **kwargs)
  File "/home/emicugno/workspace/projects/p_sigcaw/env/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 166, in __init__
    self.db_tablespace = db_tablespace or settings.DEFAULT_INDEX_TABLESPACE
  File "/home/emicugno/workspace/projects/p_sigcaw/env/lib/python3.5/site-packages/django/conf/__init__.py", line 55, in __getattr__
    self._setup(name)
  File "/home/emicugno/workspace/projects/p_sigcaw/env/lib/python3.5/site-packages/django/conf/__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/emicugno/workspace/projects/p_sigcaw/env/lib/python3.5/site-packages/django/conf/__init__.py", line 120, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.

Supuse que era, como dice al final, problema de la SECRET_KEY, pero tengo actualizado al día el repositorio en mi disco duro, existe la carpeta envdir y manage.py tiene la modificación... Alguna idea?

**Comment by lokiyin** [comment]
La carpeta envdir tiene creado una variable de entorno?

**Comment by Gnoq** [comment]
Si, dentro de la carpeta está la variable SECRET_KEY

**Comment by lokiyin** [comment]
Y tiene un valor la variable?

**Comment by rafaelferrero** [comment]
Pudiste hacerlo andar??
Tenes que tener la carpeta envdir al mismo nivel que settings.py. Dentro de
esa carpeta poner una archivo llamado SECRET_KEY (así, todo mayusculas y
sin extension) y, como contenido del archivo, cualquier texto.

Obviamente tenes que tener instalado el paquete envdir que está en el
requirements.txt, fijate con pip freeze (con el ambiente activado)



Rafael E. Ferrero

2016-12-10 14:11 GMT-03:00 lokiyin <notifications@github.com>:

**Comment by rafaelferrero** [comment]
@Gnoq ¿Pudiste hacer andar el proyecto? de ser así cerrá esta issue.
Gracias !!
